version: 1.0.{build}
image: ubuntu
stack: node 10

cache:
  - node_modules -> package.json

install:
  - sh: ls -l /usr/bin
  - sh: pwd
  - sh: ls -l
  - sh: export CHROME_BIN=/usr/bin/google-chrome
  - sh: env | sort
  - npm ci
  - node --version
  - npm --version

build: off

test_script:
  - npm run lint
  - npm test -- --progress=false
  - npm run e2e
